mavros:
  ros__parameters: {}

mavros_router:
  ros__parameters: {}

mavros_node:
  ros__parameters:
    fcu_url: udp://:14540@
    gcs_url: tcp-l://:5670

/**:
  ros__parameters:
    plugin_denylist: [odometry]
    # plugin_allowlist: []